name: ci

on:
  push:
    branches:
      - main
    paths:
      - 'src/**'
      - 'test/**'
      - '.github/workflows/*.yml'
      - 'pom.xml'
  pull_request:
    branches:
      - main
    paths:
      - 'src/**'
      - 'test/**'
      - '.github/workflows/*.yml'
      - 'pom.xml'

jobs:
  misc:
    name: General tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: 'maven'
      - name: Verify
        run: mvn -B package -DskipTests=true

  cockroachdb:
    name: DBMS Tests (CockroachDB)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: 'maven'
      - name: Build Dqetool
        run: mvn -B package -DskipTests=true
      - name: Run CockroachDB Tests
        run: mvn test -Dtest=dqetool.dbms.TestCockroachDB

  mysql:
    name: DBMS Tests (MySQL)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: 'maven'
      - name: Build Dqetool
        run: mvn -B package -DskipTests=true
      - name: Run Tests
        run: |
          mvn test -Dtest=dqetool.dbms.TestMySQLTLP
          mvn test -Dtest=dqetool.dbms.TestMySQLPQ
