name: ci

on:
  push:
    branches:
      - main
    paths:
      - 'src/**'
      - 'test/**'
      - 'pom.xml'
  pull_request:
    branches:
      - main
    paths:
      - 'src/**'
      - 'test/**'
      - 'pom.xml'

jobs:
  misc:
    name: General tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: 'maven'
      # - name: Verify
      #   run: mvn -B verify -DskipTests=true
     
  
